<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{

		public function getUserSummary()
    {
			return $this->getUsername()." <".$this->getEmailAddress ().">";
		}


		public function getAgencySummary()
    {
			$a_affectations = $this->getCrdmgrUserAgency();
			$o_agency = $a_affectations [0] ->getCtrAgency();
			return $o_agency->getAgencySummary();
		}
}