<?php

/**
 * BaseCrdmgrParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property string $type_parametre
 * @property string $code_parametre
 * @property string $label_param
 * @property decimal $valeur_string
 * @property decimal $valeur_numeric
 * @property string $description_param
 * @property integer $created_by
 * @property integer $updated_by
 * @property sfGuardUser $CtrCreatedBy
 * @property sfGuardUser $CtrUpdatedBy
 * 
 * @method boolean         getIsActive()          Returns the current record's "is_active" value
 * @method string          getTypeParametre()     Returns the current record's "type_parametre" value
 * @method string          getCodeParametre()     Returns the current record's "code_parametre" value
 * @method string          getLabelParam()        Returns the current record's "label_param" value
 * @method decimal         getValeurString()      Returns the current record's "valeur_string" value
 * @method decimal         getValeurNumeric()     Returns the current record's "valeur_numeric" value
 * @method string          getDescriptionParam()  Returns the current record's "description_param" value
 * @method integer         getCreatedBy()         Returns the current record's "created_by" value
 * @method integer         getUpdatedBy()         Returns the current record's "updated_by" value
 * @method sfGuardUser     getCtrCreatedBy()      Returns the current record's "CtrCreatedBy" value
 * @method sfGuardUser     getCtrUpdatedBy()      Returns the current record's "CtrUpdatedBy" value
 * @method CrdmgrParameter setIsActive()          Sets the current record's "is_active" value
 * @method CrdmgrParameter setTypeParametre()     Sets the current record's "type_parametre" value
 * @method CrdmgrParameter setCodeParametre()     Sets the current record's "code_parametre" value
 * @method CrdmgrParameter setLabelParam()        Sets the current record's "label_param" value
 * @method CrdmgrParameter setValeurString()      Sets the current record's "valeur_string" value
 * @method CrdmgrParameter setValeurNumeric()     Sets the current record's "valeur_numeric" value
 * @method CrdmgrParameter setDescriptionParam()  Sets the current record's "description_param" value
 * @method CrdmgrParameter setCreatedBy()         Sets the current record's "created_by" value
 * @method CrdmgrParameter setUpdatedBy()         Sets the current record's "updated_by" value
 * @method CrdmgrParameter setCtrCreatedBy()      Sets the current record's "CtrCreatedBy" value
 * @method CrdmgrParameter setCtrUpdatedBy()      Sets the current record's "CtrUpdatedBy" value
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrdmgrParameter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crdmgr_parameter');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('type_parametre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('code_parametre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('label_param', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('valeur_string', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('valeur_numeric', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('description_param', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as CtrCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}