<?php

/**
 * BaseRdFacture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $detailmirroir_id
 * @property RdDetailMirroir $fk_facture
 * 
 * @method integer         getDetailmirroirId()  Returns the current record's "detailmirroir_id" value
 * @method RdDetailMirroir getFkFacture()        Returns the current record's "fk_facture" value
 * @method RdFacture       setDetailmirroirId()  Sets the current record's "detailmirroir_id" value
 * @method RdFacture       setFkFacture()        Sets the current record's "fk_facture" value
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRdFacture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rd_facture');
        $this->hasColumn('detailmirroir_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RdDetailMirroir as fk_facture', array(
             'local' => 'detailmirroir_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}