<?php

/**
 * BaseGlassPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property string $label
 * @property string $type
 * @property decimal $price
 * @property integer $created_by
 * @property integer $updated_by
 * @property sfGuardUser $CtrCreatedBy
 * @property sfGuardUser $CtrUpdatedBy
 * @property Doctrine_Collection $Estimation
 * 
 * @method boolean             getIsActive()     Returns the current record's "is_active" value
 * @method string              getLabel()        Returns the current record's "label" value
 * @method string              getType()         Returns the current record's "type" value
 * @method decimal             getPrice()        Returns the current record's "price" value
 * @method integer             getCreatedBy()    Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()    Returns the current record's "updated_by" value
 * @method sfGuardUser         getCtrCreatedBy() Returns the current record's "CtrCreatedBy" value
 * @method sfGuardUser         getCtrUpdatedBy() Returns the current record's "CtrUpdatedBy" value
 * @method Doctrine_Collection getEstimation()   Returns the current record's "Estimation" collection
 * @method GlassPrice          setIsActive()     Sets the current record's "is_active" value
 * @method GlassPrice          setLabel()        Sets the current record's "label" value
 * @method GlassPrice          setType()         Sets the current record's "type" value
 * @method GlassPrice          setPrice()        Sets the current record's "price" value
 * @method GlassPrice          setCreatedBy()    Sets the current record's "created_by" value
 * @method GlassPrice          setUpdatedBy()    Sets the current record's "updated_by" value
 * @method GlassPrice          setCtrCreatedBy() Sets the current record's "CtrCreatedBy" value
 * @method GlassPrice          setCtrUpdatedBy() Sets the current record's "CtrUpdatedBy" value
 * @method GlassPrice          setEstimation()   Sets the current record's "Estimation" collection
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGlassPrice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('glass_price');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('label', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('type', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => false,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as CtrCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Estimation', array(
             'local' => 'id',
             'foreign' => 'glassprice_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}