<?php

/**
 * BaseDevis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property decimal $largeur
 * @property decimal $hauteur
 * @property decimal $type
 * @property decimal $prix
 * @property integer $codetype
 * @property Doctrine_Collection $fk_detail
 * 
 * @method boolean             getIsActive()  Returns the current record's "is_active" value
 * @method decimal             getLargeur()   Returns the current record's "largeur" value
 * @method decimal             getHauteur()   Returns the current record's "hauteur" value
 * @method decimal             getType()      Returns the current record's "type" value
 * @method decimal             getPrix()      Returns the current record's "prix" value
 * @method integer             getCodetype()  Returns the current record's "codetype" value
 * @method Doctrine_Collection getFkDetail()  Returns the current record's "fk_detail" collection
 * @method Devis               setIsActive()  Sets the current record's "is_active" value
 * @method Devis               setLargeur()   Sets the current record's "largeur" value
 * @method Devis               setHauteur()   Sets the current record's "hauteur" value
 * @method Devis               setType()      Sets the current record's "type" value
 * @method Devis               setPrix()      Sets the current record's "prix" value
 * @method Devis               setCodetype()  Sets the current record's "codetype" value
 * @method Devis               setFkDetail()  Sets the current record's "fk_detail" collection
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('devis');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('largeur', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('hauteur', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('prix', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('codetype', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estimation as fk_detail', array(
             'local' => 'nombre_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}