<?php

/**
 * BaseRdMirroir
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property decimal $largeur
 * @property decimal $hauteur
 * @property integer $nombre_id
 * @property Doctrine_Collection $fk_detail
 * @property Doctrine_Collection $RdDetailMirroir
 * 
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method decimal             getLargeur()         Returns the current record's "largeur" value
 * @method decimal             getHauteur()         Returns the current record's "hauteur" value
 * @method integer             getNombreId()        Returns the current record's "nombre_id" value
 * @method Doctrine_Collection getFkDetail()        Returns the current record's "fk_detail" collection
 * @method Doctrine_Collection getRdDetailMirroir() Returns the current record's "RdDetailMirroir" collection
 * @method RdMirroir           setIsActive()        Sets the current record's "is_active" value
 * @method RdMirroir           setLargeur()         Sets the current record's "largeur" value
 * @method RdMirroir           setHauteur()         Sets the current record's "hauteur" value
 * @method RdMirroir           setNombreId()        Sets the current record's "nombre_id" value
 * @method RdMirroir           setFkDetail()        Sets the current record's "fk_detail" collection
 * @method RdMirroir           setRdDetailMirroir() Sets the current record's "RdDetailMirroir" collection
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRdMirroir extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rd_mirroir');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('largeur', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('hauteur', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('nombre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RdDetailMirroir as fk_detail', array(
             'local' => 'nombre_id',
             'foreign' => 'id'));

        $this->hasMany('RdDetailMirroir', array(
             'local' => 'id',
             'foreign' => 'mirroir_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}