<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/11/19 11:43:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=simucefinal',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
