<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/11/19 14:45:55
sfConfig::add(array(
  'mod_portedeuxbattant_enabled' => true,
  'mod_portedeuxbattant_view_class' => 'sfPHP',
));
