<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/11/20 13:39:14
sfConfig::add(array(
  'mod_porteunbattant_enabled' => true,
  'mod_porteunbattant_view_class' => 'sfPHP',
));
