<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/11/20 13:42:56
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'assureur',
        1 => 'bank_operator',
        2 => 'master_operator',
      ),
    ),
  ),
);
