<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/11/19 11:43:39
sfConfig::add(array(
  'mod_detailporteunbattant_enabled' => true,
  'mod_detailporteunbattant_view_class' => 'sfPHP',
));
