<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/11/19 14:45:58
sfConfig::add(array(
  'mod_detailportedeuxbattant_enabled' => true,
  'mod_detailportedeuxbattant_view_class' => 'sfPHP',
));
