<?php

/**
 * CrdmgrParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrdmgrParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrdmgrParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CrdmgrParameter');
    }
}