<?php

/**
 * CrdmgrClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrdmgrClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrdmgrClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CrdmgrClient');
    }
}