<?php

/**
 * CrdmgrAgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrdmgrAgencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrdmgrAgencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CrdmgrAgency');
    }
}