<?php

/**
 * CrdmgrUserAgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrdmgrUserAgencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrdmgrUserAgencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CrdmgrUserAgency');
    }
}