<?php

/**
 * devis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Rdv
 * @subpackage model
 * @author     Bongas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class devis extends Basedevis
{

}