<?php

/**
 * devisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class devisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object devisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('devis');
    }
}