<?php

/**
 * EstimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estim');
    }
}