<?php

/**
 * EstimationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstimationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstimationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estimation');
    }
}