<?php

/**
 * GlassPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simuce
 * @subpackage model
 * @author     UCE - Désire Talla Tueguem
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GlassPrice extends BaseGlassPrice
{

}