<?php

/**
 * GlassPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GlassPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GlassPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GlassPrice');
    }
}