<?php

/**
 * RdDetailMirroirTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RdDetailMirroirTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RdDetailMirroirTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RdDetailMirroir');
    }
}