<?php

/**
 * RdDetailMirroir
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simuce
 * @subpackage model
 * @author     UCE - Désire Talla Tueguem
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RdDetailMirroir extends BaseRdDetailMirroir
{
// $this->embedRelations(array(
 // 'CanardCategorie' => array(
 // 'considerNewFormEmptyFields' => array('largeur_min'),
 // 'multipleNewForms'              => true,
 // 'newFormsInitialCount'          => 1,
 // 'newRelationButtonLabel'        => '+',
 // 'formClassArgs'                 => array(array('ah_add_delete_checkbox' => true)),
 // )
 // ));
}