<?php

/**
 * RdFactureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RdFactureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RdFactureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RdFacture');
    }
}