<?php

/**
 * RdMirroirTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RdMirroirTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RdMirroirTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RdMirroir');
    }
}