# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    # no_script_name:         true
    logging_enabled:        true
    # -- ajouter par tchac
    # cache:                  false
    no_script_name:         false
    # enabled_modules: [sfGuardAuth]

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              false
    cache:                  false
    no_script_name:         false
    etag:                   false
    # enabled_modules: [sfGuardAuth]

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    enabled_modules:      [default, sfGuardAuth,tmcTwitterBootstrap]
    # Form security secret (CSRF protection)
    csrf_secret:            96fcb6e6814e2cc2167813da3533409ffc69a0d8

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Change the default login and secure modules
    login_module:   sfGuardAuth
    login_action:   signin
    secure_module:  sfGuardAuth
    secure_action:  secure
    debug:    false