<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    protected $agencySummary = NULL;

    public function getUserSummary()
    {
        return  $this->getUsername()." <".$this->getEmailAddress ().">";
    }

    public function getUserAccountSummary()
    {
        return $this->getUsername()." <".$this->getFirstName() ." " .$this->getLastName().">";
    }

    public function getAgencySummary()
    {
        if ($this->agencySummary == NULL)
        {
            $a_affectations = $this->getCrdmgrUserAgency();
            $o_agency = $a_affectations [0] ->getCtrAgency();
            $this->agencySummary = $o_agency->getAgencySummary();
        }

        return $this->agencySummary;
    }
}