<?php

/**
 * BaseCrdmgrAgency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property string $code_agence
 * @property string $nom_agence
 * @property string $adresse
 * @property string $lieu_localisation_code
 * @property integer $institution_id
 * @property integer $created_by
 * @property integer $updated_by
 * @property CrdmgrInstitution $CtrInstitution
 * @property CrdmgrParameter $CtrParamLocalisation
 * @property sfGuardUser $CtrCreatedBy
 * @property sfGuardUser $CtrUpdatedBy
 * @property Doctrine_Collection $CrdmgrUserAgency
 * @property Doctrine_Collection $CrdmgrCustomer
 * @property Doctrine_Collection $CrdmgrFicheConsentement
 * @property Doctrine_Collection $CrdmgrBulletinAdhesion
 * 
 * @method boolean             getIsActive()                Returns the current record's "is_active" value
 * @method string              getCodeAgence()              Returns the current record's "code_agence" value
 * @method string              getNomAgence()               Returns the current record's "nom_agence" value
 * @method string              getAdresse()                 Returns the current record's "adresse" value
 * @method string              getLieuLocalisationCode()    Returns the current record's "lieu_localisation_code" value
 * @method integer             getInstitutionId()           Returns the current record's "institution_id" value
 * @method integer             getCreatedBy()               Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()               Returns the current record's "updated_by" value
 * @method CrdmgrInstitution   getCtrInstitution()          Returns the current record's "CtrInstitution" value
 * @method CrdmgrParameter     getCtrParamLocalisation()    Returns the current record's "CtrParamLocalisation" value
 * @method sfGuardUser         getCtrCreatedBy()            Returns the current record's "CtrCreatedBy" value
 * @method sfGuardUser         getCtrUpdatedBy()            Returns the current record's "CtrUpdatedBy" value
 * @method Doctrine_Collection getCrdmgrUserAgency()        Returns the current record's "CrdmgrUserAgency" collection
 * @method Doctrine_Collection getCrdmgrCustomer()          Returns the current record's "CrdmgrCustomer" collection
 * @method Doctrine_Collection getCrdmgrFicheConsentement() Returns the current record's "CrdmgrFicheConsentement" collection
 * @method Doctrine_Collection getCrdmgrBulletinAdhesion()  Returns the current record's "CrdmgrBulletinAdhesion" collection
 * @method CrdmgrAgency        setIsActive()                Sets the current record's "is_active" value
 * @method CrdmgrAgency        setCodeAgence()              Sets the current record's "code_agence" value
 * @method CrdmgrAgency        setNomAgence()               Sets the current record's "nom_agence" value
 * @method CrdmgrAgency        setAdresse()                 Sets the current record's "adresse" value
 * @method CrdmgrAgency        setLieuLocalisationCode()    Sets the current record's "lieu_localisation_code" value
 * @method CrdmgrAgency        setInstitutionId()           Sets the current record's "institution_id" value
 * @method CrdmgrAgency        setCreatedBy()               Sets the current record's "created_by" value
 * @method CrdmgrAgency        setUpdatedBy()               Sets the current record's "updated_by" value
 * @method CrdmgrAgency        setCtrInstitution()          Sets the current record's "CtrInstitution" value
 * @method CrdmgrAgency        setCtrParamLocalisation()    Sets the current record's "CtrParamLocalisation" value
 * @method CrdmgrAgency        setCtrCreatedBy()            Sets the current record's "CtrCreatedBy" value
 * @method CrdmgrAgency        setCtrUpdatedBy()            Sets the current record's "CtrUpdatedBy" value
 * @method CrdmgrAgency        setCrdmgrUserAgency()        Sets the current record's "CrdmgrUserAgency" collection
 * @method CrdmgrAgency        setCrdmgrCustomer()          Sets the current record's "CrdmgrCustomer" collection
 * @method CrdmgrAgency        setCrdmgrFicheConsentement() Sets the current record's "CrdmgrFicheConsentement" collection
 * @method CrdmgrAgency        setCrdmgrBulletinAdhesion()  Sets the current record's "CrdmgrBulletinAdhesion" collection
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrdmgrAgency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crdmgr_agency');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('code_agence', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('nom_agence', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('adresse', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('lieu_localisation_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('institution_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CrdmgrInstitution as CtrInstitution', array(
             'local' => 'institution_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrParameter as CtrParamLocalisation', array(
             'local' => 'lieu_localisation_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('sfGuardUser as CtrCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('CrdmgrUserAgency', array(
             'local' => 'id',
             'foreign' => 'agence_id'));

        $this->hasMany('CrdmgrCustomer', array(
             'local' => 'id',
             'foreign' => 'agence_id'));

        $this->hasMany('CrdmgrFicheConsentement', array(
             'local' => 'id',
             'foreign' => 'agence_id'));

        $this->hasMany('CrdmgrBulletinAdhesion', array(
             'local' => 'id',
             'foreign' => 'agence_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}