<?php

/**
 * BaseCrdmgrFicheConsentement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $workflow_status_code
 * @property string $workflow_status_msg
 * @property string $workflow_status_msglog
 * @property string $code_fiche_consentement
 * @property integer $customer_id
 * @property string $loan_type_code
 * @property decimal $main_amount
 * @property decimal $interest_amount
 * @property decimal $assured_amount
 * @property integer $loan_duration_months_count
 * @property decimal $accessory_amount
 * @property decimal $other_amount
 * @property decimal $montant_prime_net
 * @property decimal $total_prime_amount
 * @property timestamp $assurance_effect_date
 * @property timestamp $first_monthly_payment_date
 * @property timestamp $assurance_end_date
 * @property decimal $taux_applique
 * @property decimal $taux_supplementaire
 * @property string $cust_nom
 * @property string $cust_prenom
 * @property timestamp $cust_date_naissance
 * @property string $cust_lieu_naissance_code
 * @property string $cust_profession
 * @property string $cust_adresse
 * @property string $cust_societe_employeur
 * @property string $cust_nbre_annee_prof_code
 * @property string $cust_categ_revenu_mensuel_code
 * @property string $cust_categorie_prof_code
 * @property integer $agence_id
 * @property integer $institution_id
 * @property integer $created_by
 * @property integer $updated_by
 * @property CrdmgrParameter $CtrParamNbreAnnePro
 * @property CrdmgrParameter $CtrParamCategoryRevenuMois
 * @property CrdmgrParameter $CtrParamCategoryProfessionel
 * @property CrdmgrParameter $CtrParamWorkflowStatus
 * @property CrdmgrParameter $CtrParamLoanType
 * @property CrdmgrCustomer $CtrCustomer
 * @property CrdmgrInstitution $CtrInstitution
 * @property CrdmgrAgency $CtrAgency
 * @property sfGuardUser $CtrCreatedBy
 * @property sfGuardUser $CtrUpdatedBy
 * @property Doctrine_Collection $FicheConsentementDetails
 * 
 * @method string                  getWorkflowStatusCode()             Returns the current record's "workflow_status_code" value
 * @method string                  getWorkflowStatusMsg()              Returns the current record's "workflow_status_msg" value
 * @method string                  getWorkflowStatusMsglog()           Returns the current record's "workflow_status_msglog" value
 * @method string                  getCodeFicheConsentement()          Returns the current record's "code_fiche_consentement" value
 * @method integer                 getCustomerId()                     Returns the current record's "customer_id" value
 * @method string                  getLoanTypeCode()                   Returns the current record's "loan_type_code" value
 * @method decimal                 getMainAmount()                     Returns the current record's "main_amount" value
 * @method decimal                 getInterestAmount()                 Returns the current record's "interest_amount" value
 * @method decimal                 getAssuredAmount()                  Returns the current record's "assured_amount" value
 * @method integer                 getLoanDurationMonthsCount()        Returns the current record's "loan_duration_months_count" value
 * @method decimal                 getAccessoryAmount()                Returns the current record's "accessory_amount" value
 * @method decimal                 getOtherAmount()                    Returns the current record's "other_amount" value
 * @method decimal                 getMontantPrimeNet()                Returns the current record's "montant_prime_net" value
 * @method decimal                 getTotalPrimeAmount()               Returns the current record's "total_prime_amount" value
 * @method timestamp               getAssuranceEffectDate()            Returns the current record's "assurance_effect_date" value
 * @method timestamp               getFirstMonthlyPaymentDate()        Returns the current record's "first_monthly_payment_date" value
 * @method timestamp               getAssuranceEndDate()               Returns the current record's "assurance_end_date" value
 * @method decimal                 getTauxApplique()                   Returns the current record's "taux_applique" value
 * @method decimal                 getTauxSupplementaire()             Returns the current record's "taux_supplementaire" value
 * @method string                  getCustNom()                        Returns the current record's "cust_nom" value
 * @method string                  getCustPrenom()                     Returns the current record's "cust_prenom" value
 * @method timestamp               getCustDateNaissance()              Returns the current record's "cust_date_naissance" value
 * @method string                  getCustLieuNaissanceCode()          Returns the current record's "cust_lieu_naissance_code" value
 * @method string                  getCustProfession()                 Returns the current record's "cust_profession" value
 * @method string                  getCustAdresse()                    Returns the current record's "cust_adresse" value
 * @method string                  getCustSocieteEmployeur()           Returns the current record's "cust_societe_employeur" value
 * @method string                  getCustNbreAnneeProfCode()          Returns the current record's "cust_nbre_annee_prof_code" value
 * @method string                  getCustCategRevenuMensuelCode()     Returns the current record's "cust_categ_revenu_mensuel_code" value
 * @method string                  getCustCategorieProfCode()          Returns the current record's "cust_categorie_prof_code" value
 * @method integer                 getAgenceId()                       Returns the current record's "agence_id" value
 * @method integer                 getInstitutionId()                  Returns the current record's "institution_id" value
 * @method integer                 getCreatedBy()                      Returns the current record's "created_by" value
 * @method integer                 getUpdatedBy()                      Returns the current record's "updated_by" value
 * @method CrdmgrParameter         getCtrParamNbreAnnePro()            Returns the current record's "CtrParamNbreAnnePro" value
 * @method CrdmgrParameter         getCtrParamCategoryRevenuMois()     Returns the current record's "CtrParamCategoryRevenuMois" value
 * @method CrdmgrParameter         getCtrParamCategoryProfessionel()   Returns the current record's "CtrParamCategoryProfessionel" value
 * @method CrdmgrParameter         getCtrParamWorkflowStatus()         Returns the current record's "CtrParamWorkflowStatus" value
 * @method CrdmgrParameter         getCtrParamLoanType()               Returns the current record's "CtrParamLoanType" value
 * @method CrdmgrCustomer          getCtrCustomer()                    Returns the current record's "CtrCustomer" value
 * @method CrdmgrInstitution       getCtrInstitution()                 Returns the current record's "CtrInstitution" value
 * @method CrdmgrAgency            getCtrAgency()                      Returns the current record's "CtrAgency" value
 * @method sfGuardUser             getCtrCreatedBy()                   Returns the current record's "CtrCreatedBy" value
 * @method sfGuardUser             getCtrUpdatedBy()                   Returns the current record's "CtrUpdatedBy" value
 * @method Doctrine_Collection     getFicheConsentementDetails()       Returns the current record's "FicheConsentementDetails" collection
 * @method CrdmgrFicheConsentement setWorkflowStatusCode()             Sets the current record's "workflow_status_code" value
 * @method CrdmgrFicheConsentement setWorkflowStatusMsg()              Sets the current record's "workflow_status_msg" value
 * @method CrdmgrFicheConsentement setWorkflowStatusMsglog()           Sets the current record's "workflow_status_msglog" value
 * @method CrdmgrFicheConsentement setCodeFicheConsentement()          Sets the current record's "code_fiche_consentement" value
 * @method CrdmgrFicheConsentement setCustomerId()                     Sets the current record's "customer_id" value
 * @method CrdmgrFicheConsentement setLoanTypeCode()                   Sets the current record's "loan_type_code" value
 * @method CrdmgrFicheConsentement setMainAmount()                     Sets the current record's "main_amount" value
 * @method CrdmgrFicheConsentement setInterestAmount()                 Sets the current record's "interest_amount" value
 * @method CrdmgrFicheConsentement setAssuredAmount()                  Sets the current record's "assured_amount" value
 * @method CrdmgrFicheConsentement setLoanDurationMonthsCount()        Sets the current record's "loan_duration_months_count" value
 * @method CrdmgrFicheConsentement setAccessoryAmount()                Sets the current record's "accessory_amount" value
 * @method CrdmgrFicheConsentement setOtherAmount()                    Sets the current record's "other_amount" value
 * @method CrdmgrFicheConsentement setMontantPrimeNet()                Sets the current record's "montant_prime_net" value
 * @method CrdmgrFicheConsentement setTotalPrimeAmount()               Sets the current record's "total_prime_amount" value
 * @method CrdmgrFicheConsentement setAssuranceEffectDate()            Sets the current record's "assurance_effect_date" value
 * @method CrdmgrFicheConsentement setFirstMonthlyPaymentDate()        Sets the current record's "first_monthly_payment_date" value
 * @method CrdmgrFicheConsentement setAssuranceEndDate()               Sets the current record's "assurance_end_date" value
 * @method CrdmgrFicheConsentement setTauxApplique()                   Sets the current record's "taux_applique" value
 * @method CrdmgrFicheConsentement setTauxSupplementaire()             Sets the current record's "taux_supplementaire" value
 * @method CrdmgrFicheConsentement setCustNom()                        Sets the current record's "cust_nom" value
 * @method CrdmgrFicheConsentement setCustPrenom()                     Sets the current record's "cust_prenom" value
 * @method CrdmgrFicheConsentement setCustDateNaissance()              Sets the current record's "cust_date_naissance" value
 * @method CrdmgrFicheConsentement setCustLieuNaissanceCode()          Sets the current record's "cust_lieu_naissance_code" value
 * @method CrdmgrFicheConsentement setCustProfession()                 Sets the current record's "cust_profession" value
 * @method CrdmgrFicheConsentement setCustAdresse()                    Sets the current record's "cust_adresse" value
 * @method CrdmgrFicheConsentement setCustSocieteEmployeur()           Sets the current record's "cust_societe_employeur" value
 * @method CrdmgrFicheConsentement setCustNbreAnneeProfCode()          Sets the current record's "cust_nbre_annee_prof_code" value
 * @method CrdmgrFicheConsentement setCustCategRevenuMensuelCode()     Sets the current record's "cust_categ_revenu_mensuel_code" value
 * @method CrdmgrFicheConsentement setCustCategorieProfCode()          Sets the current record's "cust_categorie_prof_code" value
 * @method CrdmgrFicheConsentement setAgenceId()                       Sets the current record's "agence_id" value
 * @method CrdmgrFicheConsentement setInstitutionId()                  Sets the current record's "institution_id" value
 * @method CrdmgrFicheConsentement setCreatedBy()                      Sets the current record's "created_by" value
 * @method CrdmgrFicheConsentement setUpdatedBy()                      Sets the current record's "updated_by" value
 * @method CrdmgrFicheConsentement setCtrParamNbreAnnePro()            Sets the current record's "CtrParamNbreAnnePro" value
 * @method CrdmgrFicheConsentement setCtrParamCategoryRevenuMois()     Sets the current record's "CtrParamCategoryRevenuMois" value
 * @method CrdmgrFicheConsentement setCtrParamCategoryProfessionel()   Sets the current record's "CtrParamCategoryProfessionel" value
 * @method CrdmgrFicheConsentement setCtrParamWorkflowStatus()         Sets the current record's "CtrParamWorkflowStatus" value
 * @method CrdmgrFicheConsentement setCtrParamLoanType()               Sets the current record's "CtrParamLoanType" value
 * @method CrdmgrFicheConsentement setCtrCustomer()                    Sets the current record's "CtrCustomer" value
 * @method CrdmgrFicheConsentement setCtrInstitution()                 Sets the current record's "CtrInstitution" value
 * @method CrdmgrFicheConsentement setCtrAgency()                      Sets the current record's "CtrAgency" value
 * @method CrdmgrFicheConsentement setCtrCreatedBy()                   Sets the current record's "CtrCreatedBy" value
 * @method CrdmgrFicheConsentement setCtrUpdatedBy()                   Sets the current record's "CtrUpdatedBy" value
 * @method CrdmgrFicheConsentement setFicheConsentementDetails()       Sets the current record's "FicheConsentementDetails" collection
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrdmgrFicheConsentement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crdmgr_fiche_consentement');
        $this->hasColumn('workflow_status_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('workflow_status_msg', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('workflow_status_msglog', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('code_fiche_consentement', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('loan_type_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('main_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('interest_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('assured_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('loan_duration_months_count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('accessory_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('other_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('montant_prime_net', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('total_prime_amount', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('assurance_effect_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2010-01-01 00:00:00',
             ));
        $this->hasColumn('first_monthly_payment_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2010-01-01 00:00:00',
             ));
        $this->hasColumn('assurance_end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2010-01-01 00:00:00',
             ));
        $this->hasColumn('taux_applique', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('taux_supplementaire', 'decimal', 16, array(
             'type' => 'decimal',
             'notnull' => true,
             'size' => 16,
             'scale' => 4,
             'default' => 0,
             'length' => 16,
             ));
        $this->hasColumn('cust_nom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_prenom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_date_naissance', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '1990-01-01 00:00:00',
             ));
        $this->hasColumn('cust_lieu_naissance_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_profession', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_adresse', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_societe_employeur', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_nbre_annee_prof_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_categ_revenu_mensuel_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cust_categorie_prof_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('agence_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('institution_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CrdmgrParameter as CtrParamNbreAnnePro', array(
             'local' => 'cust_nbre_annee_prof_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamCategoryRevenuMois', array(
             'local' => 'cust_categ_revenu_mensuel_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamCategoryProfessionel', array(
             'local' => 'cust_categorie_prof_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamWorkflowStatus', array(
             'local' => 'workflow_status_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamLoanType', array(
             'local' => 'loan_type_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrCustomer as CtrCustomer', array(
             'local' => 'customer_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrInstitution as CtrInstitution', array(
             'local' => 'institution_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrAgency as CtrAgency', array(
             'local' => 'agence_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('CrdmgrFicheConsentementDetail as FicheConsentementDetails', array(
             'local' => 'id',
             'foreign' => 'fiche_consentement_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}