<?php

/**
 * BaseCrdmgrFicheConsentementDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fiche_consentement_id
 * @property integer $question_id
 * @property boolean $bool_answer
 * @property string $string_answer
 * @property CrdmgrFicheConsentement $CtrFicheConsentement
 * @property CrdmgrParameter $CtrQuestion
 * 
 * @method integer                       getFicheConsentementId()   Returns the current record's "fiche_consentement_id" value
 * @method integer                       getQuestionId()            Returns the current record's "question_id" value
 * @method boolean                       getBoolAnswer()            Returns the current record's "bool_answer" value
 * @method string                        getStringAnswer()          Returns the current record's "string_answer" value
 * @method CrdmgrFicheConsentement       getCtrFicheConsentement()  Returns the current record's "CtrFicheConsentement" value
 * @method CrdmgrParameter               getCtrQuestion()           Returns the current record's "CtrQuestion" value
 * @method CrdmgrFicheConsentementDetail setFicheConsentementId()   Sets the current record's "fiche_consentement_id" value
 * @method CrdmgrFicheConsentementDetail setQuestionId()            Sets the current record's "question_id" value
 * @method CrdmgrFicheConsentementDetail setBoolAnswer()            Sets the current record's "bool_answer" value
 * @method CrdmgrFicheConsentementDetail setStringAnswer()          Sets the current record's "string_answer" value
 * @method CrdmgrFicheConsentementDetail setCtrFicheConsentement()  Sets the current record's "CtrFicheConsentement" value
 * @method CrdmgrFicheConsentementDetail setCtrQuestion()           Sets the current record's "CtrQuestion" value
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrdmgrFicheConsentementDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crdmgr_fiche_consentement_detail');
        $this->hasColumn('fiche_consentement_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bool_answer', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('string_answer', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CrdmgrFicheConsentement as CtrFicheConsentement', array(
             'local' => 'fiche_consentement_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrParameter as CtrQuestion', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}