<?php

/**
 * BaseCrdmgrCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property string $code_client
 * @property string $nom
 * @property string $prenom
 * @property string $titre_code
 * @property timestamp $date_naissance
 * @property string $lieu_naissance_code
 * @property string $sexe_code
 * @property string $statut_marital_code
 * @property string $adresse
 * @property string $telephone
 * @property string $email
 * @property string $type_piece_identite_code
 * @property string $numero_identite
 * @property timestamp $date_delivrance_identite
 * @property string $lieu_delivrance_identite
 * @property timestamp $date_expiration_identite
 * @property string $profession
 * @property string $societe_employeur
 * @property string $secteur_activite
 * @property timestamp $date_debut_service
 * @property string $lieu_residence
 * @property string $lieu_travail
 * @property string $categorie_professionel_code
 * @property string $categorie_revenu_mensuel_code
 * @property string $nbre_annee_professionel_code
 * @property string $autres_sources_revenu
 * @property string $autres_assurances
 * @property integer $agence_id
 * @property integer $institution_id
 * @property integer $created_by
 * @property integer $updated_by
 * @property CrdmgrInstitution $CtrInstitution
 * @property CrdmgrAgency $CtrAgency
 * @property CrdmgrParameter $CtrParamSexe
 * @property CrdmgrParameter $CtrParamTitre
 * @property CrdmgrParameter $CtrParamStatutMarital
 * @property CrdmgrParameter $CtrParamTypeIdentite
 * @property CrdmgrParameter $CtrParamNbreAnnePro
 * @property CrdmgrParameter $CtrParamCategoryRevenuMois
 * @property CrdmgrParameter $CtrParamCategoryProfessionel
 * @property sfGuardUser $CtrCreatedBy
 * @property sfGuardUser $CtrUpdatedBy
 * @property Doctrine_Collection $CrdmgrFicheConsentement
 * @property Doctrine_Collection $CrdmgrBulletinAdhesion
 * 
 * @method boolean             getIsActive()                      Returns the current record's "is_active" value
 * @method string              getCodeClient()                    Returns the current record's "code_client" value
 * @method string              getNom()                           Returns the current record's "nom" value
 * @method string              getPrenom()                        Returns the current record's "prenom" value
 * @method string              getTitreCode()                     Returns the current record's "titre_code" value
 * @method timestamp           getDateNaissance()                 Returns the current record's "date_naissance" value
 * @method string              getLieuNaissanceCode()             Returns the current record's "lieu_naissance_code" value
 * @method string              getSexeCode()                      Returns the current record's "sexe_code" value
 * @method string              getStatutMaritalCode()             Returns the current record's "statut_marital_code" value
 * @method string              getAdresse()                       Returns the current record's "adresse" value
 * @method string              getTelephone()                     Returns the current record's "telephone" value
 * @method string              getEmail()                         Returns the current record's "email" value
 * @method string              getTypePieceIdentiteCode()         Returns the current record's "type_piece_identite_code" value
 * @method string              getNumeroIdentite()                Returns the current record's "numero_identite" value
 * @method timestamp           getDateDelivranceIdentite()        Returns the current record's "date_delivrance_identite" value
 * @method string              getLieuDelivranceIdentite()        Returns the current record's "lieu_delivrance_identite" value
 * @method timestamp           getDateExpirationIdentite()        Returns the current record's "date_expiration_identite" value
 * @method string              getProfession()                    Returns the current record's "profession" value
 * @method string              getSocieteEmployeur()              Returns the current record's "societe_employeur" value
 * @method string              getSecteurActivite()               Returns the current record's "secteur_activite" value
 * @method timestamp           getDateDebutService()              Returns the current record's "date_debut_service" value
 * @method string              getLieuResidence()                 Returns the current record's "lieu_residence" value
 * @method string              getLieuTravail()                   Returns the current record's "lieu_travail" value
 * @method string              getCategorieProfessionelCode()     Returns the current record's "categorie_professionel_code" value
 * @method string              getCategorieRevenuMensuelCode()    Returns the current record's "categorie_revenu_mensuel_code" value
 * @method string              getNbreAnneeProfessionelCode()     Returns the current record's "nbre_annee_professionel_code" value
 * @method string              getAutresSourcesRevenu()           Returns the current record's "autres_sources_revenu" value
 * @method string              getAutresAssurances()              Returns the current record's "autres_assurances" value
 * @method integer             getAgenceId()                      Returns the current record's "agence_id" value
 * @method integer             getInstitutionId()                 Returns the current record's "institution_id" value
 * @method integer             getCreatedBy()                     Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()                     Returns the current record's "updated_by" value
 * @method CrdmgrInstitution   getCtrInstitution()                Returns the current record's "CtrInstitution" value
 * @method CrdmgrAgency        getCtrAgency()                     Returns the current record's "CtrAgency" value
 * @method CrdmgrParameter     getCtrParamSexe()                  Returns the current record's "CtrParamSexe" value
 * @method CrdmgrParameter     getCtrParamTitre()                 Returns the current record's "CtrParamTitre" value
 * @method CrdmgrParameter     getCtrParamStatutMarital()         Returns the current record's "CtrParamStatutMarital" value
 * @method CrdmgrParameter     getCtrParamTypeIdentite()          Returns the current record's "CtrParamTypeIdentite" value
 * @method CrdmgrParameter     getCtrParamNbreAnnePro()           Returns the current record's "CtrParamNbreAnnePro" value
 * @method CrdmgrParameter     getCtrParamCategoryRevenuMois()    Returns the current record's "CtrParamCategoryRevenuMois" value
 * @method CrdmgrParameter     getCtrParamCategoryProfessionel()  Returns the current record's "CtrParamCategoryProfessionel" value
 * @method sfGuardUser         getCtrCreatedBy()                  Returns the current record's "CtrCreatedBy" value
 * @method sfGuardUser         getCtrUpdatedBy()                  Returns the current record's "CtrUpdatedBy" value
 * @method Doctrine_Collection getCrdmgrFicheConsentement()       Returns the current record's "CrdmgrFicheConsentement" collection
 * @method Doctrine_Collection getCrdmgrBulletinAdhesion()        Returns the current record's "CrdmgrBulletinAdhesion" collection
 * @method CrdmgrCustomer      setIsActive()                      Sets the current record's "is_active" value
 * @method CrdmgrCustomer      setCodeClient()                    Sets the current record's "code_client" value
 * @method CrdmgrCustomer      setNom()                           Sets the current record's "nom" value
 * @method CrdmgrCustomer      setPrenom()                        Sets the current record's "prenom" value
 * @method CrdmgrCustomer      setTitreCode()                     Sets the current record's "titre_code" value
 * @method CrdmgrCustomer      setDateNaissance()                 Sets the current record's "date_naissance" value
 * @method CrdmgrCustomer      setLieuNaissanceCode()             Sets the current record's "lieu_naissance_code" value
 * @method CrdmgrCustomer      setSexeCode()                      Sets the current record's "sexe_code" value
 * @method CrdmgrCustomer      setStatutMaritalCode()             Sets the current record's "statut_marital_code" value
 * @method CrdmgrCustomer      setAdresse()                       Sets the current record's "adresse" value
 * @method CrdmgrCustomer      setTelephone()                     Sets the current record's "telephone" value
 * @method CrdmgrCustomer      setEmail()                         Sets the current record's "email" value
 * @method CrdmgrCustomer      setTypePieceIdentiteCode()         Sets the current record's "type_piece_identite_code" value
 * @method CrdmgrCustomer      setNumeroIdentite()                Sets the current record's "numero_identite" value
 * @method CrdmgrCustomer      setDateDelivranceIdentite()        Sets the current record's "date_delivrance_identite" value
 * @method CrdmgrCustomer      setLieuDelivranceIdentite()        Sets the current record's "lieu_delivrance_identite" value
 * @method CrdmgrCustomer      setDateExpirationIdentite()        Sets the current record's "date_expiration_identite" value
 * @method CrdmgrCustomer      setProfession()                    Sets the current record's "profession" value
 * @method CrdmgrCustomer      setSocieteEmployeur()              Sets the current record's "societe_employeur" value
 * @method CrdmgrCustomer      setSecteurActivite()               Sets the current record's "secteur_activite" value
 * @method CrdmgrCustomer      setDateDebutService()              Sets the current record's "date_debut_service" value
 * @method CrdmgrCustomer      setLieuResidence()                 Sets the current record's "lieu_residence" value
 * @method CrdmgrCustomer      setLieuTravail()                   Sets the current record's "lieu_travail" value
 * @method CrdmgrCustomer      setCategorieProfessionelCode()     Sets the current record's "categorie_professionel_code" value
 * @method CrdmgrCustomer      setCategorieRevenuMensuelCode()    Sets the current record's "categorie_revenu_mensuel_code" value
 * @method CrdmgrCustomer      setNbreAnneeProfessionelCode()     Sets the current record's "nbre_annee_professionel_code" value
 * @method CrdmgrCustomer      setAutresSourcesRevenu()           Sets the current record's "autres_sources_revenu" value
 * @method CrdmgrCustomer      setAutresAssurances()              Sets the current record's "autres_assurances" value
 * @method CrdmgrCustomer      setAgenceId()                      Sets the current record's "agence_id" value
 * @method CrdmgrCustomer      setInstitutionId()                 Sets the current record's "institution_id" value
 * @method CrdmgrCustomer      setCreatedBy()                     Sets the current record's "created_by" value
 * @method CrdmgrCustomer      setUpdatedBy()                     Sets the current record's "updated_by" value
 * @method CrdmgrCustomer      setCtrInstitution()                Sets the current record's "CtrInstitution" value
 * @method CrdmgrCustomer      setCtrAgency()                     Sets the current record's "CtrAgency" value
 * @method CrdmgrCustomer      setCtrParamSexe()                  Sets the current record's "CtrParamSexe" value
 * @method CrdmgrCustomer      setCtrParamTitre()                 Sets the current record's "CtrParamTitre" value
 * @method CrdmgrCustomer      setCtrParamStatutMarital()         Sets the current record's "CtrParamStatutMarital" value
 * @method CrdmgrCustomer      setCtrParamTypeIdentite()          Sets the current record's "CtrParamTypeIdentite" value
 * @method CrdmgrCustomer      setCtrParamNbreAnnePro()           Sets the current record's "CtrParamNbreAnnePro" value
 * @method CrdmgrCustomer      setCtrParamCategoryRevenuMois()    Sets the current record's "CtrParamCategoryRevenuMois" value
 * @method CrdmgrCustomer      setCtrParamCategoryProfessionel()  Sets the current record's "CtrParamCategoryProfessionel" value
 * @method CrdmgrCustomer      setCtrCreatedBy()                  Sets the current record's "CtrCreatedBy" value
 * @method CrdmgrCustomer      setCtrUpdatedBy()                  Sets the current record's "CtrUpdatedBy" value
 * @method CrdmgrCustomer      setCrdmgrFicheConsentement()       Sets the current record's "CrdmgrFicheConsentement" collection
 * @method CrdmgrCustomer      setCrdmgrBulletinAdhesion()        Sets the current record's "CrdmgrBulletinAdhesion" collection
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrdmgrCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crdmgr_customer');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('code_client', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('prenom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('titre_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_naissance', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '1990-01-01 00:00:00',
             ));
        $this->hasColumn('lieu_naissance_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('sexe_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('statut_marital_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('adresse', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('telephone', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('type_piece_identite_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('numero_identite', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_delivrance_identite', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2000-01-01 00:00:00',
             ));
        $this->hasColumn('lieu_delivrance_identite', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_expiration_identite', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2000-01-01 00:00:00',
             ));
        $this->hasColumn('profession', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('societe_employeur', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('secteur_activite', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('date_debut_service', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'default' => '2000-01-01 00:00:00',
             ));
        $this->hasColumn('lieu_residence', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('lieu_travail', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('categorie_professionel_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('categorie_revenu_mensuel_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('nbre_annee_professionel_code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('autres_sources_revenu', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('autres_assurances', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('agence_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('institution_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CrdmgrInstitution as CtrInstitution', array(
             'local' => 'institution_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrAgency as CtrAgency', array(
             'local' => 'agence_id',
             'foreign' => 'id'));

        $this->hasOne('CrdmgrParameter as CtrParamSexe', array(
             'local' => 'sexe_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamTitre', array(
             'local' => 'titre_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamStatutMarital', array(
             'local' => 'statut_marital_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamTypeIdentite', array(
             'local' => 'type_piece_identite_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamNbreAnnePro', array(
             'local' => 'nbre_annee_professionel_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamCategoryRevenuMois', array(
             'local' => 'categorie_revenu_mensuel_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('CrdmgrParameter as CtrParamCategoryProfessionel', array(
             'local' => 'categorie_professionel_code',
             'foreign' => 'code_parametre'));

        $this->hasOne('sfGuardUser as CtrCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as CtrUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('CrdmgrFicheConsentement', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $this->hasMany('CrdmgrBulletinAdhesion', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}