<?php

/**
 * CrdmgrCommissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CrdmgrCommissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CrdmgrCommissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CrdmgrCommission');
    }
}