<?php

/**
 * CrdmgrParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CrdmgrParameter extends BaseCrdmgrParameter
{

	public function __toString()
	{
		return sprintf('%s', $this->getLabelParam());
	}

	/*
	public function __toString()
	{
		return sprintf('%s at %s (%s)', $this->getPosition(), $this->getCompany(), $this->getLocation());
	}*/

	public function save(Doctrine_Connection $conn = null)
	{
		// preciser les infos nécessaire avant la sauvegarde: created_by, updated_by
		/*
		if (!$this->getCreatedBy())
		{
			$this->setCreatedBy(sha1($this->getEmail().rand(11111, 99999)));
		}
		*/
		return parent::save($conn);	
	}



}