<?php

/**
 * CrdmgrInstitution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    credit_mng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CrdmgrInstitution extends BaseCrdmgrInstitution
{

	public function getTypeInstitutionCodeLite()
	{
		return myAdminHelper::getLiteHelper ( $this->getTypeInstitutionCode () );
	} 

	  public  function getInstitutionSummary()
    {
			return $this->getNomInstitution();
		}

}